### ISSUE TITLE
Pledge -> statement?

### ISSUE THREAD

**Issue by takluyver** [python3statement/python3statement.github.io#1]
Pledge:

> A solemn binding promise to do, give, or refrain from doing something

It sounds a bit dramatic and self-sacrificing. That has its good points - a 'pledge' might get more attention than a 'statement'. But I think it will also be harder to get people to sign if it sounds like they're promising to do something risky.

I favour publicly calling this a 'statement', with the implication that we're just highlighting what we were already going to do. The common base level should be "we won't support Python 2 beyond 2020", which doesn't feel controversial or dramatic. Then individual projects can add details to go further, e.g. bugfixes only for Python 2, or ending support before 2020.

**Comment by Carreau** [comment]
Sure no problem with renaming it. You are the english speaker.

Can we rename an org ?

**Comment by Carreau** [comment]
Also just playing around with timelines:

<img width="689" alt="screen shot 2016-04-20 at 12 27 33" src="https://cloud.githubusercontent.com/assets/335567/14671666/57ba5552-06f3-11e6-8478-e7fe9cb87d98.png">

(random dates of course)
