### ISSUE TITLE
SSL certificate issues

### ISSUE THREAD

**Issue by rth** [python3statement/python3statement.github.io#104]
Currently, the SSL certificate for https://www.python3statement.org/ appears to be invalid,
```
wget https://www.python3statement.org/ 
--2018-02-14 09:10:15--  https://www.python3statement.org/
Resolving www.python3statement.org... 151.101.61.147, 2a04:4e42:f::403
Connecting to www.python3statement.org|151.101.61.147|:443... connected.
The certificate's owner does not match hostname ‘www.python3statement.org’
```
anyone else seeing the same error? (I also get warning pages in Firefox and Chrome).

**Comment by takluyver** [comment]
This is a limitation of hosting websites on Github pages - the SSL certificate only covers the default `foo.github.io` address. It doesn't work if you have a custom domain. We just have to point people to the unencrypted version.

**Comment by rth** [comment]
Aww, you are right, thanks. I'm not sure how I ended up on the https version, I am fairly sure I didn't type https manually in the address bar, it must have been a link somewhere..

**Comment by Carreau** [comment]
Let's reopen, I'll see if we can setup something like netlify in front of it that can get correct ssl certificate.

**Comment by Carreau** [comment]
@asmeurer, @takluyver, requesting authorization to change DNS nameservers to netlify ones to get automatic https letsencrypt certificate.

**Comment by Carreau** [comment]
That would be setting the DN servers to : 

```
dns1.p01.nsone.net
dns2.p01.nsone.net
dns3.p01.nsone.net
dns4.p01.nsone.net
```

Mirror deployment is there: 

https://python3statement.netlify.com/

Once DNS is set and propagated it's a  click button to get an https certificate. I can make you admin of the netlify deployment as well of course.

**Comment by takluyver** [comment]
Fine by me. Will it still be automatically updated when we push to Github?

**Comment by Carreau** [comment]
Yes.

**Comment by Carreau** [comment]
> Fine by me. Will it still be automatically updated when we push to Github?

On top of that, each PR is also built and get it's random subdomain, so we can check each PR before merging.

**Comment by takluyver** [comment]
Fancy!

**Comment by Carreau** [comment]
Ok, https should be valid now.

**Comment by takluyver** [comment]
Indeed it is - nice work!
