### ISSUE TITLE
2.7 EOL = 2020 January 1

### ISSUE THREAD

**Issue by fmaussion** [python3statement/python3statement.github.io#106]
Seen on the Python ML today:

https://mail.python.org/pipermail/python-list/2018-March/731770.html

**Comment by takluyver** [comment]
Thanks for the heads up!

**Comment by mscuthbert** [comment]
Yes!  My original message was misunderstood, but it did have a good effect!

**Comment by Carreau** [comment]
Updates were merged in master in a31c23d08c11ec7c5f282ed759b2bfd26b01ca2e and similar commits. Closing ! Thanks !
