### ISSUE TITLE
Add license file

### ISSUE THREAD

**Issue by pganssle** [python3statement/python3statement.github.io#109]
It's not clear what the license situation is for this repository. Can you add some information about how content is licensed?

It might be good to also clarify something about image use as well, if people are going to be adding their project logos. Not sure if there are boilerplate terms for that situation - e.g. the logos are fair use or by making a PR you are granting a non-transferrable non-exclusive right to use the logo for the purposes of this website, something of that nature.

**Comment by takluyver** [comment]
I'd say the text content is CC-BY, and any code is MIT or similar, or even public domain.

Logos... myeh, I'd be inclined to say that life's to short to define the exact legal status of them. We check when people add a project that they're a maintainer or they have the support of the maintainers, so I think we can be satisfied that the projects are happy for us to use their logos. Logos are covered by trademark law as well as copyright, and that's got a load of different complexities.

**Comment by Carreau** [comment]
Agreed with TK. CC-BY, and public domain for code.

**Comment by takluyver** [comment]
@pganssle does #110 look OK to you? I don't really know how to apply a mixture of licenses, so it's not a simple LICENSE file.

**Comment by takluyver** [comment]
Closed by #110.
