### ISSUE TITLE
IPython timeline

### ISSUE THREAD

**Issue by mscuthbert** [python3statement/python3statement.github.io#114]
Not part of the IPython/Jupyter team, but according to the timeline they should be on v. 7, but there's no movement on releasing a version 7 at present.  Any objections to my extending v. 6 by a year and pushing other versions back?  It's strange to make a unilateral move on someone else's project but I think it'd be helpful.

**Comment by Carreau** [comment]
Yeah, we should update, thomas just released IPython 6.3 and master is python 3.4+ and will be 7.0 since this morning.

I'll update.
