### ISSUE TITLE
Ask/Followup on SymPy.

### ISSUE THREAD

**Issue by Carreau** [python3statement/python3statement.github.io#13]
Just opening issues for some people we want to contact.

**Comment by takluyver** [comment]
Ping @asmeurer - did you get a chance to bring this up with other Sympy developers?

**Comment by asmeurer** [comment]
No, I've been busy with other stuff. I'll do it now.

**Comment by asmeurer** [comment]
https://groups.google.com/forum/#!topic/sympy/3SXUEjeNhrM

**Comment by takluyver** [comment]
Thanks Aaron!

**Comment by Carreau** [comment]
Thanks !

**Comment by asmeurer** [comment]
It sounds like people are in support.  I'd like to let it sit for a few more days to see if anyone else comments. 

Regarding the site, SymPy doesn't really have a release schedule. We just do releases and bump version numbers. I guess I can just make up a number (say, 2.0 will be first Py3 only release).

**Comment by asmeurer** [comment]
It's been a week, and everyone who's responded has been supportive. So I think we can add SymPy to the list.

**Comment by takluyver** [comment]
Thanks Aaron. This is starting to look like a proper list now. @Carreau, who're we asking next?

**Comment by Carreau** [comment]
from the top of my head it would be nice to try to contact people from :

- Django 
- yt – `ngoldbaum` ?
- sklearn 
- seaborn [Michael Waskom]
- astropy 

Though I'm not quite sure of how much pro py2 they would be. 

Though I'm not a BDFL here.

**Comment by fmaussion** [comment]
see also statsmodels:
https://groups.google.com/forum/#!topic/pystatsmodels/sn1gszEhx2I
