### ISSUE TITLE
Adding Pants build tool

### ISSUE THREAD

**Issue by Eric-Arellano** [python3statement/python3statement.github.io#139]
Hello, I'm leading Pants' migration to Python 3, and am wondering if you'd be interested in them joining the statement?

Pants is an open source build-tool for multilingual monorepos, used by Twitter, Foursquare, Medium, Square, and a few other firms and startups. Competitor to Bazel and Buck.

They want to drop Py2 completely within the next two major releases, which should be well before January 2020.

See https://github.com/pantsbuild/pants/issues/6062 for the migration plan and I'll ask the maintainers if they're willing to sign (I'm a contributor who's been working closely with them).

**Comment by Eric-Arellano** [comment]
Great! Two potential blockers for adding:

1) We're about two weeks away from finishing the port to Python 3. I don't know if you require the library to already be ported.
2) We haven't committed to a firm deadline with dates, beyond knowing that we plan to drop within two major releases, which should be well before Jan 2020. I see there is both the list and the timeline, so maybe this is enough for the list?

Let me know if either needs to be addressed before submitting a PR.

**Comment by takluyver** [comment]
That's ok: it's not necessary to have already ported it, or to have a firm
release date. It's sufficient if the developers of the project are on board
with an intention to require python 3 by 2020.

**Comment by benjyw** [comment]
I'd like to clarify something here: We are talking about Pants itself requiring py3 to run, and utilizing py3 features in its own codebase. 

But we intend it to be able to build py2 code (while itself running on py3) into the far future, certainly beyond Jan 2020.

So, 

A) I don't know if this meets the intent of this statement.

and

B) I'm not sure if Pants joining this statement might send the wrong signal to users, that we will be dropping support for building their py2 code.

**Comment by Eric-Arellano** [comment]
I'm closing this out. We discussed offline that as @benjyw brings up, Pants is probably not the right fit for this statement. 

Whereas most libraries are directly called and are going to require Python 3 to work, Pants will for a very long time support running Python 2. The tool itself will be written in Python 3, and if users want to use it as a library (a valid use case), they will need Python 3. 

But to simply use the tool, Python 2 will still work. So, the statement would create confusion.

My apologies to all for jumping the gun on this!

**Comment by takluyver** [comment]
No problem. I think that's a reasonable objection for a range of developer tools that run as command line tools rather than Python libraries. Thanks for opening the discussion!
