### ISSUE TITLE
Ask/Followup on Matplotlib

### ISSUE THREAD

**Issue by Carreau** [python3statement/python3statement.github.io#14]
Same as previous issue.

**Comment by takluyver** [comment]
For reference, here's the matplotlib-devel thread where this was raised:
https://mail.python.org/pipermail/matplotlib-devel/2016-May/000374.html

@tacaswell So far it looks like there has been no pushback on the proposed schedule, at least publicly. How long do you want to wait for responses? Have you had any private feedback on it?

**Comment by tacaswell** [comment]
I have not heard any feedback public or private,  just sent as email to try and shake the bushes a bit.

**Comment by takluyver** [comment]
It looks like there's a bit more discussion now, and it mostly seems favourable. Are you happy for us to put matplotlib on the list?

**Comment by fmaussion** [comment]
I find the few number of responses (negative or positive) very suspicious... This can only mean one thing: the scientific python community is either in phase 1 (denial) or phase 5 (acceptance) of the transition ;-) (http://www.snarky.ca/the-stages-of-the-python-3-transition)

**Comment by takluyver** [comment]
I think the community that is active on mailing lists mostly accepts it at this point. I'm sure this will still be somewhat controversial to a wider audience, but that's why we're making this statement: to communicate to people who might be assuming that we'll support Python 2.7 for ever that we're not planning to do that. Crucially, we're doing it well in advance, to lay the groundwork for dropping Python 2 support in a few years - so we're not pulling the rug out from under people suddenly.

**Comment by Carreau** [comment]
> I find the few number of responses (negative or positive) very suspicious...

I was astonished also for matplotlib, but scikit image seem to have [a bit more of a pushback](https://groups.google.com/forum/#!topic/scikit-image/7aH6hshJJg0). Discussing with numpy dev, it's not the right time to ask, even if they would like to. So my guess is that the state really depend on the project.

**Comment by takluyver** [comment]
This has made it to reddit, via Aaron's blog post, so it's probably going to get a lot of eyeballs shortly. @tacaswell , do you want us to put matplotlib on the list?

**Comment by Carreau** [comment]
It's ok, it's only on /r/python, /r/programming or frontpage pour have been
bad.

**Comment by tacaswell** [comment]
Yes, just sent a summary email to matplotlib-devel.  Would it be possible
to include a link to that discussion someplace on the webpage?

**Comment by Carreau** [comment]
> Would it be possible
> to include a link to that discussion someplace on the webpage?

Of course.

**Comment by asmeurer** [comment]
Yeah, somehow Reddit has no comments and almost no upvotes. It's number 5 on Hacker News right now, though.

**Comment by Carreau** [comment]
> Yeah, somehow Reddit has no comments and almost no upvotes. It's number 5 on Hacker News right now, though.

Ouch. 

BTW, @asmeurer want to be part of the org ? You kind of initiated that.

**Comment by asmeurer** [comment]
Sure

**Comment by Carreau** [comment]
Matplotlib is now on the list.
