### ISSUE TITLE
Add SciPy to projects

### ISSUE THREAD

**Issue by rgommers** [python3statement/python3statement.github.io#158]
Hi, sorry no time for a PR right now but wanted to already summarize the info for SciPy:

v1.2.0 will be the last release that support Python 2.7 and 3.4 (release date mid-Dec 2018). It will be an LTS release, with backports until 1 Jan 2020.

**Comment by takluyver** [comment]
Thanks @rgommers, we can add SciPy for you if you like. Have you had a discussion with any other maintainers about signing the statement?

Would it make sense to use [this logo](https://docs.scipy.org/doc/scipy-0.10.1/reference/_static/scipyshiny_small.png)?

**Comment by rgommers** [comment]
Thanks Thomas, that would be great. And yes, that's the right logo.

**Comment by jakirkham** [comment]
Just checking in. Anything else needed for this?

**Comment by takluyver** [comment]
I just haven't got round to it. If you want to make a pull request, that might speed things up. :-)

**Comment by jakirkham** [comment]
Ok, wasn't sure if there was more than that. Thanks for clarifying.

Maybe PR ( https://github.com/python3statement/python3statement.github.io/pull/167 ) helps? Not sure if I did it right. So please feel free to change as needed.
