### ISSUE TITLE
Add Bokeh

### ISSUE THREAD

**Issue by bryevdv** [python3statement/python3statement.github.io#161]
Please add Bokeh to the list of projects. The draft BEP describing our intended timeline is here:

https://github.com/bokeh/bokeh/wiki/BEP-5:-Python-2-Support-Timeline

And the associated core team discussion is here:

https://github.com/bokeh/bokeh/issues/8463

A PNG Bokeh logo is linked below (can provide SVG if preferred)

https://bokeh.pydata.org/en/latest/_static/images/logo.png

**Comment by takluyver** [comment]
The quickest way to make this happen is a pull request. Thanks!

**Comment by mscuthbert** [comment]
Note that in github you don't need to do a fork, pull request, etc. -- you can simply edit the code here and on submit, a new fork and pull request will be created.

**Comment by bryevdv** [comment]
Since I don't know what edits are required it's currently an unknown amount of work to me. I am not sure when I will be able to look at it, but if the onus is on me I will look at it whenever I am able. 

However, if you are not actually able to accept signatories via issue I'd gently suggest changing this statement on the front page:

> Do you want to sign the statement for your project? *Open an issue with your project information*, or directly submit a pull-request.

**Comment by takluyver** [comment]
We can in principle - once you've indicated a willingness to sign, anyone can add the logo for you. I'll tag it 'help wanted' to indicate that that's the case. But I'm busy enough that I'm unlikely to swiftly add logos for projects.

Here's a recent example pull request adding a project to show anyone interested what to do:
https://github.com/python3statement/python3statement.github.io/pull/160/files

**Comment by CAM-Gerlach** [comment]
@takluyver Bokeh was added in #191 , so this can be closed.

**Comment by takluyver** [comment]
Thanks!
