### ISSUE TITLE
"If someone wants to continue to support 2.7..."

### ISSUE THREAD

**Issue by mscuthbert** [python3statement/python3statement.github.io#166]
I see a lot of projects that have dropped or are planning on dropping Python 2 have put notes to vendors or others who want to continue to support Python 2 to contact them, etc.  Has anyone been contacted by a serious dev who wants to do so?  I'm just wondering for community information whether or not there does in fact exist a set of enthusiastic or deep-pocketed group of people interested in keeping Python 2 versions of our software alive after statement signers have moved on.

(will close in a month or sooner if this isn't a good forum for discussing)

**Comment by Carreau** [comment]
I think that if people are interested, we'd be happy to leave a trace here or on the website, but my guts tell me that most of the interested parties have not realized (yet) that Python 2 is close to EOL. 

Most big player (facebook, instagram...) have migrated to Python 3, and the other big python users that are still on Python 2 most likely don't want to have that publicized and wil likely get private contrac with companies like enthought /anaconda/quantsight to have support. 

Personally I'm totally ok to have Python 2 support for software if that allow the project to be financially sustainable and push the developpement on Python3 version.

**Comment by mscuthbert** [comment]
Closing this -- it got enough attention, and only heard chirps.  It sounds like no serious dev has taken on Py2 support on any major project.
