### ISSUE TITLE
Add Marrow projects.

### ISSUE THREAD

**Issue by amcgregor** [python3statement/python3statement.github.io#169]
Howdy!

I've committed myself to deprecation and removal of Python 2 support from participating Marrow projects within 2019Q1 to make better use of newly available language features such as function annotations.  This is notably a challenge due to adherence to the "namespaces are one honking great idea" Zen, and the [updated Python 3 semantics therein](https://packaging.python.org/guides/packaging-namespace-packages/#native-namespace-packages).  Projects include:

* [WebCore](https://github.com/marrow/webcore/) (and associated `web.*` packages; there are quite a few)
* Marrow [Schema](https://github.com/marrow/schema), [Interface](https://github.com/marrow/interface), [Script](https://github.com/marrow/script), [Mongo](https://github.com/marrow/mongo), … (participating `marrow.*` packages)
* The [Cinje](https://github.com/marrow/cinje) template engine.
* The [URI](https://github.com/marrow/uri) datatype container.

Logo (small; larger can be provided if needed):
![marrow logo small](https://user-images.githubusercontent.com/76750/50781958-ada09780-1274-11e9-87b2-2596ba8d61eb.png)

**Comment by takluyver** [comment]
Hi, thanks! Do you think people will recognise it better as one umbrella project, or as individual projects (for the more prominent ones)?

Either way, if you've got time, it would be great to open a pull request to add projects - you can see a recent example pull request here:
https://github.com/python3statement/python3statement.github.io/pull/167/files

**Comment by CAM-Gerlach** [comment]
Given their large number of projects, single logo and recognizable name, it would seem prudent to add them as one project (as others have). @amcgregor would you like me to help you out with a PR? Thanks!

**Comment by takluyver** [comment]
I'm closing all 'add $PROJECT' issues now - the statement has served its purpose and we're archiving it. Thanks!
