### ISSUE TITLE
Fancier listing of participating projects

### ISSUE THREAD

**Issue by takluyver** [python3statement/python3statement.github.io#17]
The current list of project names feels a bit cramped, although I like the 'signatories' feel to it, I think it could be nicer. At a minimum, we could make the names a bit bigger, space them out more, and lose the underlines. Going further, maybe we can put them in a 2D grid rather than a central list, possibly with project logos.

**Comment by Carreau** [comment]
> 2D grid

I [tried with CSS](https://github.com/python3statement/python3statement.github.io/blob/master/combo.css#L45-L49) but there are browser rendering issues.

Happy to add project logo for interested projects.

**Comment by takluyver** [comment]
maybe as `inline-block` divs, rather than columnising them?

**Comment by Carreau** [comment]
Could do.

<img width="681" alt="screen shot 2016-05-14 at 11 52 50" src="https://cloud.githubusercontent.com/assets/335567/15270165/6ce58b56-19ca-11e6-91f0-b0fe7a4ee25b.png">

**Comment by takluyver** [comment]
Stick some logos above that, I think it could work. Maybe the projects without logos should go in a more standard list below.

**Comment by fmaussion** [comment]
How large / influent should the projects be in order to get to the list? If small projects are also welcome I'm happy to add https://github.com/OGGM/oggm to the list.

However, I'm afraid that the small end-of-the-scientific-chain projects are not relevant enough. The upstream projects should definitely have prominence on the list display: once they make the step the others will follow. Maybe sort the projects by number of likes/forks/users/whatever?

**Comment by takluyver** [comment]
I think it's fine to list any code projects that are published for other people to use. We'll definitely be giving the better known ones more prominence, however. So far we're just estimating this based on how much we've heard of things and how general they look. Github stars is probably a good guide for projects that are on Github, but we need some solution for the few that aren't.

**Comment by Carreau** [comment]
@fmaussion Do you want to make a PR with your Project ? We can also make you a member of the org. 
I think anyone with a project added here could be made a member if they like.

**Comment by takluyver** [comment]
We've got a nicer layout now.
