### ISSUE TITLE
Add plyara

### ISSUE THREAD

**Issue by utkonos** [python3statement/python3statement.github.io#180]
Greetings,

We released plyara 2.0.0 a few weeks ago. We have dropped support for python 2 and refactored everything for 3.6/3.7.

https://github.com/plyara/plyara

**Comment by takluyver** [comment]
Thanks - do you want to make a pull request?

Here's a recent example pull request adding another project: https://github.com/python3statement/python3statement.github.io/pull/177/files

**Comment by utkonos** [comment]
We don't have a logo. What's the protocol for us?

**Comment by takluyver** [comment]
Even easier! There are two lists in the same file: one of projects with logos, one of projects without.

Just find where your project fits into the list based on number of stars, and add a line with a Markdown link.

**Comment by CAM-Gerlach** [comment]
@utkonos You want me to help you out with a PR adding it, and you can sign off, if you don't have the bandwidth? Lmk, thanks!

**Comment by utkonos** [comment]
@CAM-Gerlach Yes, that would be great!

**Comment by CAM-Gerlach** [comment]
Sure, @utkonos , will do shortly and ping you there.

**Comment by CAM-Gerlach** [comment]
@utkonos So I can fill out the support timeline (given you're dropping support earlier than Jan 1 2020), how long have you supported Python 3 before you dropped Python 2 support, or with what approx release?

**Comment by utkonos** [comment]
Thanks for taking care of this. We dropped python 2 support at the same time as releasing python 3 on Feb. 1, 2019.
