### ISSUE TITLE
Python 2 EOL Bof At SciPy

### ISSUE THREAD

**Issue by Carreau** [python3statement/python3statement.github.io#187]
@takluyver , @asmeurer will you be at SciPy ? 
Any interest in doing an end of Py2 BoF ? 
Someone else interested ?

**Comment by asmeurer** [comment]
I don't know yet if I'll be there but I am interested if I am.

**Comment by takluyver** [comment]
I won't be there, though I'd be interested if I was.

**Comment by tacaswell** [comment]
I will be there and am interested.

**Comment by tacaswell** [comment]
In private email, @rgommers suggested we merge a BoF about minimum version policy with this one (https://github.com/scipy/scipy/issues/9610).

I've started to write up an outline: https://paper.dropbox.com/doc/Python-2.7-EOL-and-minimum-version-policy--AZk_z7dksEUFm_BJfn8pumatAQ-UlswQ4d1LsQ5wtRNrMVQx

**Comment by rgommers** [comment]
Ah, this is where you got the existence of the end-of-py2 BoF from:) I'd be interested. I'm wondering who are going to be the people bringing in issues etc. though? From a core project perspective, we're basically just done I would think; keeping an LTS release for a while but that's it.

**Comment by Carreau** [comment]
> Ah, this is where you got the existence of the end-of-py2 BoF from:) I'd be interested. I'm wondering who are going to be the people bringing in issues etc. though? From a core project perspective, we're basically just done I would think; keeping an LTS release for a while but that's it.

I think there is still a lot of FUD, and people who do not know what dropping 2.7 will imply. I would be more inclined to have this bofs to inform users and smaller libraries on how to **properly** drop 2.7 support (in the sens have pip not try to install incompat version).

I'm fine merging both bofs, and if you are not  aware of BOFs it's my fault I'm late on sending emails to mailing lists about the fact that bofs submissions started yesterdays.

**Comment by rgommers** [comment]
> I'm fine merging both bofs,

Hmm, the intended audiences seem different. The version policy thing is more aimed at maintainers of core SciPy packages. We can also do it separate, whatever you think is best.

> and if you are not aware of BOFs it's my fault I'm late on sending emails to mailing lists about the fact that bofs submissions started yesterdays.

I'm aware that they exist, I just didn't see any info on which ones have been proposed on the site so was wondering where @tacaswell got his crystal ball:)

**Comment by asmeurer** [comment]
It looks like I will be at SciPy. Let me know if you want me to help with this.

By the way, I agree with @Carreau. My original impression was that this was aimed at end-users. For instance, people who are still using Python 2 and want to know what the EOL means for them. I think most library authors have already decided at this point how they are going to handle dropping Python 2, though if any haven't they are welcome to come and discuss it.

**Comment by hugovk** [comment]
I think this can be closed now :)

**Comment by takluyver** [comment]
Thanks @hugovk
