### ISSUE TITLE
add requests project

### ISSUE THREAD

**Issue by kenneth-reitz** [python3statement/python3statement.github.io#194]
Requests 3.0 will release by 2020, and will be dropping support for 2.x completely.

This is hinted at on the Requests homepage. I can make this hinting more direct, if you like.

Please email me (me@kennethreitz.org) if you have any questions. I don't get GitHub notifications reliably. Many thanks. :sparkles: :cake: :sparkles:

**Comment by takluyver** [comment]
Thanks Kenneth!

Anyone want to make a PR for this?

**Comment by hugovk** [comment]
Please see PR https://github.com/python3statement/python3statement.github.io/pull/195.
