### ISSUE TITLE
Wording

### ISSUE THREAD

**Issue by takluyver** [python3statement/python3statement.github.io#2]
In conjunction with #1, here's my attempt at drafting a statement I like more than the current one:

-----

All of the major projects making up the Scientific Python stack now support both Python 3.x and Python 2.7, and many projects have been supporting these two versions of the language for several years. While we have developed tools and techniques to maintain compatibility efficiently, it is a small but constant friction in the development of a lot of code.

We are keen to use Python 3, and we currently accept the cost of writing cross-compatible code to allow a smooth transition, but we don’t intend to maintain this indefinitely. Although the transition has not been as quick as we hoped, we do see it taking place, with more and more people using, teaching and recommending Python 3.

The developers of the Python language extended support of Python 2.7 from 2015 to 2020, recognising that many people were still using Python 2. We believe that the extra 5 years is sufficient, and our projects plan to stop supporting Python 2 when upstream support ends in 2020, if not before. We will then be able to simplify our code and take advantage of the many new features in the current version of the Python language and standard library.

In addition, significantly before 2020, some of our projects will step down Python 2.7 support to only fixing bugs, and make new feature releases which require Python 3. This too parallels support for the language itself, as Python 2.7 releases only include bugfixes and security improvements.

Third parties may offer paid support for our projects on old Python versions for longer than we support them ourselves. We won’t obstruct this, and it is a core principle of free and open source software that this is possible. However, if you enjoy the free, first party support for many projects in the Scientific Python stack, please start planning to move to Python 3.

**Comment by Carreau** [comment]
Looks good, do you want to push that in the repo directly, and should we move that to an org with a different name, move this repo there, and nuke this org ?

**Comment by Carreau** [comment]
Alternative ideas for the org ? and hence the hosting sub domain?

**Comment by Carreau** [comment]
I think we could change a bit to invite also project that are **not** from the scientific stack.

**Comment by takluyver** [comment]
I think I'd go for `python3statement`. 

We could make it broader, but I think we can give quite a simple, clear message in the scientific stack, and it gets more complicated if we broaden it - the 'all the major projects' thing becomes much more debatable. Let's leave it as is for now, and we can look at adapting it if we get major non-scientific projects wanting to sign it.

**Comment by Carreau** [comment]
Great , thanks !
