### ISSUE TITLE
Django

### ISSUE THREAD

**Issue by asmeurer** [python3statement/python3statement.github.io#23]
A HN commenter pointed out https://www.djangoproject.com/weblog/2015/jun/25/roadmap/, which claims that Django 1.11 will be the last version to support Python 2.7.

**Comment by Carreau** [comment]
Cool, does someone want to try to contact one of the django developer to ask if they want to sign here ?

**Comment by Carreau** [comment]
From Private thread, Django might go beyond 2020 (as far as we understand), if they decide to shorten and commit to drop before we can reconsider asking them.
