### ISSUE TITLE
Timeline chart not displayed

### ISSUE THREAD

**Issue by isshiki** [python3statement/python3statement.github.io#241]
![timeline-chart](https://user-images.githubusercontent.com/195644/60001806-40f24b80-96a2-11e9-9b31-b2c56e77c2c4.png)

I think that the timeline chart was displayed here when I saw timeline-section a week ago. 
But, that is not displayed today.

**Comment by isshiki** [comment]
![error](https://user-images.githubusercontent.com/195644/60002452-a09d2680-96a3-11e9-955c-f4c5ec991b96.png)

I found a javascript error.
It may be the cause?

**Comment by takluyver** [comment]
Yes, that's probably the cause. Do you want to make a PR fixing it?

This isn't the first time that's been broken. Maybe we should set up some simple CI to validate the JS syntax.

**Comment by isshiki** [comment]
Thank you.
OK. I will make PR.
