### ISSUE TITLE
Add project ‘python-daemon’

### ISSUE THREAD

**Issue by bignose-debian** [python3statement/python3statement.github.io#266]
The [`python-daemon`](https://pagure.io/python-daemon/) project maintainer intends to sign this statement.

**Comment by bignose-debian** [comment]
I do not maintain code on GitHub. Fortunately, Git is distributed, so I request a merge from [branch ‘wip/issue/266/add-project-python-daemon’](https://gitlab.com/bignose/python3statement.github.io/tree/wip/issue/266/add-project-python-daemon) in my personal fork of this repository.

Please merge from that branch to resolve this issue.

**Comment by takluyver** [comment]
Thanks, done.
