### ISSUE TITLE
Add SecureDrop

### ISSUE THREAD

**Issue by brainwane** [python3statement/python3statement.github.io#267]
Per https://securedrop.org/news/securedrop-100-released/ :

> Python update: This release transitions the SecureDrop application code and all its dependencies to run under Python 3. This is part of a full transition of SecureDrop to Python 3 before the end-of-life date for Python 2 (January 1, 2020).

> https://github.com/freedomofpress/securedrop/issues/4355
> https://github.com/freedomofpress/securedrop/pull/4622

**Comment by takluyver** [comment]
Thanks! If anyone's looking to do this, please ask the securedrop maintainers to discuss it - we always get project maintainers agreement before adding their name to the statement, even if they've dropped Python 3 support.

**Comment by takluyver** [comment]
I'm closing all 'add $PROJECT' issues now - the statement has served its purpose and we're archiving it. Thanks!
