### ISSUE TITLE
Default anaconda download

### ISSUE THREAD

**Issue by fmaussion** [python3statement/python3statement.github.io#27]
Both [anaconda](https://www.continuum.io/downloads) and [miniconda](http://conda.pydata.org/miniconda.html) download pages put py2.7 and py3.5 at the same level (arguably py2.7 even has more prominence since it's the first on the list). 

I don't know if you folks have contacts with continuum or if I am being too optimistic, but a good thing to do would be to make 3.5 a default download and make 2.7 less prominent (for example as a footnote: "btw, you can still download py2.7 if you really want to").

(my apologies if this post is OT: in that case just let me know)

**Comment by takluyver** [comment]
It's a good idea, but from discussions we've had with people at Continuum, I don't think they'll go for it. They tell us that most of their customers are still on Python 2. This is part of our motivation for doing this, to encourage more people to make the jump.

I'm glad that the two versions are now given roughly equal prominence - for a long time, the Anaconda download page showed Python 2.7, and you had to click an extra link to go to the Python 3 download page.

**Comment by fmaussion** [comment]
OK good to know, thanks! Feel free to close the issue.

**Comment by takluyver** [comment]
Thanks Fabien :-)

**Comment by asmeurer** [comment]
Getting them on the same level is already a won battle. I would suggest getting them to improve the "which one should I download?" text. It doesn't really talk about Python 2 vs. Python 3.

**Comment by asmeurer** [comment]
The miniconda download page is at https://github.com/conda/conda-docs/blob/master/web/source/miniconda.rst. I'm sure they'd be open to pull requests modifying the text there.

**Comment by jaypeedevlin** [comment]
3 is first:

![image](https://cloud.githubusercontent.com/assets/17235807/21068561/789e2008-be38-11e6-8c67-950c94cace26.png)

**Comment by Carreau** [comment]
Yeahhhhh

**Comment by takluyver** [comment]
:-)

**Comment by tacaswell** [comment]
https://github.com/conda/conda-docs/pull/386 for miniconda page.  

That one seems like a much lower priority as if you have landed on that page you have probably already decided which one you want and the UI nudge will not matter.

**Comment by fmaussion** [comment]
See also : https://github.com/conda/conda-docs/pull/387

**Comment by tacaswell** [comment]
Closing this as the mini-conda version is flipped, and the anaconda page currently has the on the same level.  

https://github.com/conda/conda-docs/pull/568 has gone in to replace See also : conda/conda-docs#387
