### ISSUE TITLE
Add lib3to6

### ISSUE THREAD

**Issue by mbarkhau** [python3statement/python3statement.github.io#285]
I have written a library called [lib3to6](https://pypi.org/project/lib3to6/).

I am unsure of the most appropriate way to add lib3to6 to python3statement.org, since a large part of the purpose (though not the whole purpose) of lib3to6 is to help with backwards compatibility for Python 2.7. In that sense, the project would not be appropriate to add to the list of participating projects.

I do feel however (biased as I am) that for some libraries, lib3to6 makes it very cheap to support Python 2.7. The most recent example where I did this was with the [pretty-traceback](https://pypi.org/project/pretty-traceback/) package.

I assume there are at least some packages that currently support both Python2 and Python3, which could benefit from this kind of automated compilation/transpilation, but who are not aware of lib3to6 as an option. They could start to use many of the Python3 language features and associated tooling such as mypy, remove much of the boilerplate such as `from __future__  import print_function` from their source repository and nonetheless retain support for Python2.7 if that is important to their users. In this way, lib3to6 can reduce the burden on maintainers to continue supporting Python2.7 if they still need to.

If/how to add lib3to6 to python3statement.org, I'm not sure. Perhaps a mention on the [practicalities](https://python3statement.org/practicalities/) page would be appropriate.

**Comment by mscuthbert** [comment]
My feeling: if `lib3to6` is written in Python 3 and not supported on Py2 then it can and should be listed; that's the only criterion we've listed.  Maybe some will think that it shouldn't be here because it allows end users to stay on Py2.7 longer, but (a) it helps more programmers move to using Py3 and that's important, and (b) it's exactly the tool that we need for going forward so that we can dump supporting Py 3.4, etc. :-)  I'm definitely +1 on listing on the projects (there's instructions for doing so, just make a PR) and for adding to practicalities page.

**Comment by mbarkhau** [comment]
Would you feel comfortable if I add a section to the [Reccomended Mitigations](https://github.com/python3statement/python3statement.github.io/blob/master/_practicalities/intro.md#recommended-mitigations)

Something to the effect of this:

If you have users that still depend on Python 2.7 and you cannot drop support yet, it may nonetheless be possible to start using Python 3 in your codebase. Through automatic conversion using [lib3to6](https://pypi.org/project/lib3to6/) (similar to BabelJS) you can generate distribution files that will work on both Python2 and Python3.

**Comment by mscuthbert** [comment]
In PR #286 -- look it over and see if it sounds good?

**Comment by mbarkhau** [comment]
@mscuthbert isn't that already merged?

**Comment by mscuthbert** [comment]
@mbarkhau -- the placement on the front page is done, but the Recommended Mitigations addition is in the new PR.

**Comment by mbarkhau** [comment]
Ahh, I looked throught the open ones. I guess you meant #287. LGTM

**Comment by ELDELORO51350** [comment]
Goodtobest
