### ISSUE TITLE
@takluyver that's correct, IAB is an interactive bioinformatics text that uses Python 3 but the code there is for educational purposes only and not intended for import (we usually refer readers to scikit-bio for that).

### ISSUE THREAD

**Issue by Azmirol** [python3statement/python3statement.github.io#289]
@takluyver that's correct, IAB is an interactive bioinformatics text that uses Python 3 but the code there is for educational purposes only and not intended for import (we usually refer readers to scikit-bio for that).

👍 for differentiating if there's more projects added like this.

_Originally posted by @jairideout in https://github.com/python3statement/python3statement.github.io/issues/33#issuecomment-229714617_

**Comment by takluyver** [comment]
You've copied a comment to a new issue (and helpfully given attribution). I don't know if you're confused or a malfunctioning bot. :confused:
