### ISSUE TITLE
Add Gala and some other projects

### ISSUE THREAD

**Issue by Carreau** [python3statement/python3statement.github.io#29]
@jni, gala is Py3 only right ? 

You told me you had other Py3 only repos ?

Do you want to add these to this website ?

**Comment by jni** [comment]
@Carreau Yes, gala is Python 3 only in master, and I'd be happy to add it to this list. [Microscopium](https://github.com/microscopium/microscopium) is currently unreleased but I'll add it also once it is released.

If it was up to me I would add scikit-image, too. @stefanv? ;)

**Comment by Carreau** [comment]
> If it was up to me I would add scikit-image, too. @stefanv? ;)

I think @stevanv already asked on SciKit Image Mailing list :-)

**Comment by jni** [comment]
Yes, I'm just asking him to synthesise that thread and make the correct choice here. ;)

**Comment by takluyver** [comment]
I've just scanned through [that sckikit-image thread](https://groups.google.com/forum/#!topic/scikit-image/7aH6hshJJg0), and there is not a clear consensus. Some people argued the case for institutional users stuck on old Pythons, others pointed out that conda can be installed without admin rights, providing a way to get newer versions of Python than the system offers.

As the last message was over a month ago, I think we'll need to prompt further discussion in the scikit-image community to reach a conclusion. Maybe pointing out our statement would help to tilt the balance - it wasn't mentioned in the thread so far.

**Comment by Carreau** [comment]
I'll poke @stefanv once back in Berkeley tomorrow. I think he is busy with preparing SciPy.

**Comment by brettcannon** [comment]
@Carreau that poke ever lead to anything?

**Comment by Carreau** [comment]
> @Carreau that poke ever lead to anything?

I'll repoke him, I think he was/is busy with writing elegant SciPy.

**Comment by stefanv** [comment]
I will revisit the issue.
​

**Comment by CAM-Gerlach** [comment]
@takluyver Gala and Scikit-Image are on the list now and microscopium still appears unreleased, so looks like this can be closed.

BTW, have you considered a minimum star/user threshold, to avoid projects that aren't currently used by many more people than their authors, or those just seeking free publicity, from adding their names (any current projects would be grandfathered). Perhaps a minimum of ~25-50 stars, top 10 000 on PyPI or special exception by the maintainers here would be appropriate (with any current projects under that limit grandfathered in)? I can open an issue to discuss if you think its worthwhile.

**Comment by takluyver** [comment]
Thanks @CAM-Gerlach .

I hadn't thought about that. I do quite like the open feel of including both big and small projects together, rather than an exclusive club. But on the other hand, I'm aware that the page is getting ever bigger, both in pixels and in bytes. Feel free to open an issue to discuss it further.

Maybe it would be a reasonable compromise to let any project add their name to the list, but have logos only for projects above some popularity threshold.

**Comment by CAM-Gerlach** [comment]
@takluyver It tends to be that only projects meeting that sort of threshold generally have logos anyway, so I tend to think its not worth the potential turnoff to do so. Of the ~70-odd projects with logos, only 3 have under 50 stars (~5, ~5 and 15). So, I think I'll leave it for now, thanks.
