### ISSUE TITLE
Make a list of projects fully switched to python3 only

### ISSUE THREAD

**Issue by sciunto** [python3statement/python3statement.github.io#34]
As there were websites listing projects supporting python3, when python3 appeared (like http://py3readiness.org/), I think it would help to convince users if we make a list of project that only release new versions with python3 support only.

**Comment by takluyver** [comment]
I think this will be a good thing to do in a year or two - at the moment, I think that list is probably too short to be really compelling.

**Comment by sciunto** [comment]
Good point. We can keep that behind the scene for now.

**Comment by Carreau** [comment]
Yes, there is also https://python3wos.appspot.com/, and the difference is that you can alway install an old version that support Python 2, while you couldn't install a future version that woudl have supported python 3 :- p

**Comment by takluyver** [comment]
> you couldn't install a future version

You mean that's not what `pip install --pre` is for?! :P

**Comment by Carreau** [comment]
> You mean that's not what pip install --pre is for?! :P

Point taken.

**Comment by Carreau** [comment]
> You mean that's not what pip install --pre is for?! :P

Technically I think `--pre` also an alias for `--with-more-bugs`.

**Comment by mscuthbert** [comment]
Close, given the timeline chart?
