### ISSUE TITLE
Engage discussion with Astropy.

### ISSUE THREAD

**Issue by Carreau** [python3statement/python3statement.github.io#40]
Talked with @astrofrog a bit today.
Opening issue to track.

**Comment by astrofrog** [comment]
There was some initial (positive) discussion about signing the python 3 statement a few weeks ago: https://groups.google.com/forum/#!topic/astropy-dev/0pumTIoqV5Q - before we do vote on signing this, we want to come up with a concrete plan of action for future releases.

**Comment by takluyver** [comment]
Closed by #47
