### ISSUE TITLE
Make it clearer that projects are dropping Python 2 support

### ISSUE THREAD

**Issue by takluyver** [python3statement/python3statement.github.io#51]
I [posted](https://www.reddit.com/r/Python/comments/594lpz/python_3_support_in_scientific_python_projects/) the page to the Python subreddit, and the comment with the most votes currently is pointing out that this is about projects dropping Python 2 support, not adding Python 3 support.

Looking at the page again, it's easy to see why people are confused: the page title is *Python 3 support in scientific Python projects* (this is also the title on the reddit link). And if you skim the page without reading the statement text, it's not at all obvious what the 'Participating projects' are participating in.

I think we should:

- [x] Make a clearer page title
- [ ] Have the top header say something clearer than 'Python 3 Statement' (e.g. 'Moving to Python 3 by default'?)
- [ ] Add a sentence above the project logos highlighting what the list means.

**Comment by asmeurer** [comment]
Something like "Statement of commitment for dropping Python 2 support by 2020"?

**Comment by Carreau** [comment]
+1

**Comment by takluyver** [comment]
Yup, sounds good. I'm about to go to sleep over on this side of the world; feel free to make PRs or commit directly in your fancy American time zones. ;-)
