### ISSUE TITLE
Real domain?

### ISSUE THREAD

**Issue by asmeurer** [python3statement/python3statement.github.io#54]
Any interest in putting this under a real domain? python3statement.org is avaiable.

**Comment by takluyver** [comment]
I think that would be a good idea. @Carreau or I could register it. We also wondered about seeing if Numfocus would be willing to support it.

**Comment by asmeurer** [comment]
Well I went ahead and got the domain (on namecheap). Let me know if you want to transfer it somewhere. http://www.python3statement.org/

I'll also add you guys as managers.

**Comment by asmeurer** [comment]
@Carreau what's your email? It's not on your GitHub profile.

**Comment by takluyver** [comment]
Thanks Aaron! I successfully joined it on namecheap.
