### ISSUE TITLE
Projects ordering

### ISSUE THREAD

**Issue by takluyver** [python3statement/python3statement.github.io#57]
We've tried to order projects roughly by prominence, using Github stars as a proxy. Projects with logos also come before those without, for aesthetic reasons. Reviewing #56, I noticed that some of them are now out of order because they've gained more stars (xonsh in particular has got a lot more stars now).

- What do we do for projects that aren't on Github, or don't have a single main repository on Github (like Software Carpentry)?
- Do we try to group related projects together (e.g. Jupyter & IPython)
- Do we differentiate documentation/teaching projects from software packages? (SC, IAB)
- Do we treat xonsh specially? We're kind of considering it an honorary scientific Python package because Anthony is part of our community, but I suspect it's less familiar to people in this community than more specifically scientific packages which may have fewer stars.

**Comment by Carreau** [comment]
I think contributor have always been ok adding things at the end. I doubt order make a (huge) difference. 

I don't think we _need_ to start separating project by categories yet. If we had more in categories we could start thinking about this. I don't want to start having a "metric" yet either. Everybody have been reasonable for now. So I would say that : 
   Order is up to the committers , roughly we try to follow "popularity" of packages, we use GitHub stars as a "guide".

**Comment by takluyver** [comment]
Sounds reasonable. I'll leave this open as a place for ideas on what to do when Github stars aren't a useful guide, though.

**Comment by asmeurer** [comment]
I think it's worth thinking about how to handle things if the number of projects increases by an order of magnitude or more. I would also consider not just restricting the site to scientific Python (although that community seems to be the most on board with this).

**Comment by Carreau** [comment]
If it grows **a lot** we need a separate page that list all project and have a search/filter IMHO. And we likely need to blend download numbers from PyPI.

**Comment by asmeurer** [comment]
PyPI doesn't have download numbers anymore.

**Comment by Carreau** [comment]
> PyPI doesn't have download numbers anymore.

https://bigquery.cloud.google.com/table/the-psf:pypi.downloads

**Comment by Carreau** [comment]
```
SELECT REGEXP_EXTRACT(file.version, r'^(\d+.\d+)') as major_version,  COUNT(file.version) as downloads
FROM (TABLE_DATE_RANGE([the-psf:pypi.downloads], 
                TIMESTAMP('2016-06-26'), 
                TIMESTAMP('2016-08-31'))) 
WHERE file.project == 'ipython'
GROUP BY major_version
ORDER BY major_version DESC
```

```
1	5.1	292393	 
2	5.0	544449	 
3	4.2	216291	 
4	4.1	51630	 
5	4.0	86978	 
6	3.2	47066	 
7	3.1	17265	 
8	3.0	12788	 
9	2.4	13889	
```

**Comment by takluyver** [comment]
As for restricting it to scientific python, my rationale so far is that I'd
rather present it as a substantial part of this particular ecosystem,
rather than a much smaller part of the general python ecosystem. That's
certainly up for reevaluation at any point, though.

**Comment by asmeurer** [comment]
I just suspect that if this gets presented at pycon that a lot more people will be interested.

**Comment by takluyver** [comment]
That's a good point. I think we can present it as coming from the scientific Python community, while saying that it's open for Python projects more generally to join.

**Comment by takluyver** [comment]
I think we need to look at this again. We've got rid of the limitation to scientific Python projects. But before we did that, some popular projects like Kivy and Zulip snuck in near the bottom of the list, so that the top couple of rows would be focused on scientific projects.

I'm leaning towards re-sorting the projects by popularity, now that 'scientific-ness' is no longer a criteria? Alternatively, we could try to develop a more explicit categorisation of the signatories.

**Comment by asmeurer** [comment]
If the list is big enough splitting into categories could be helpful. I like the stars rule for ordering either way, though. It's a simple rule and no one can argue with it.

**Comment by takluyver** [comment]
I have a minor concern about how to rank a project that isn't on Github - or something like software carpentry, which is on Github, but isn't directly comparable to a software package. That's why I tell people that the stars metric is a 'rough proxy' for popularity. But it hasn't been a big issue yet, so I plan to keep using it.

As we gain more signatories, in some ways the message is shifting from showing *which* projects are taking this step to showing that lots of projects are, including high profile ones. To me, this points towards sticking with one big list.

**Comment by takluyver** [comment]
I've just reordered them based on Github stars, plus a bit of my own judgment for things like software carpentry. As expected, this means a much broader range of categories are represented at the top of the list.

**Comment by mscuthbert** [comment]
Closing -- well updated, and #228 is going to keep this problem well under control.
