### ISSUE TITLE
The `rpy2` project seems to be about there. 

### ISSUE THREAD

**Issue by lgautier** [python3statement/python3statement.github.io#61]
The target Python version for rpy2 is 3.5, and there are already Python 3-only features (and no Python 2-only features...).

**Comment by takluyver** [comment]
Thanks Laurent! Do you think you'll be making Python 3 only releases by 2020? Would you like to add rpy2 to the statement?

**Comment by lgautier** [comment]
Sure. If you need a logo you can snatch it from the doc page: http://rpy2.readthedocs.io/en/version_2.8.x/

I tried making rpy2 Python 3-only 4-5 years ago but I quickly realized that the world was not yet ready for that. Now seems the right time if there is a coordinated movement of the data-oriented Python ecosystem in that direction.

If the Gantt chart on the page is accurate, and projects do start with Python-3 only next year I am ready to make the current rpy2 release series (2.8.x) an LTS and make the next release series (2.9.x) Python 3-only (or if too much push back from user, this would be with 2.10.x in about a year / a year and a half).

**Comment by Carreau** [comment]
> If the Gantt chart on the page is accurate, and projects do start with Python-3 only next year I am ready to make the current rpy2 release series (2.8.x) an LTS and make the next release series (2.9.x) Python 3-only (or if too much push back from user, this would be with 2.10.x in about a year / a year and a half).

It should be about time. I'm working on (hopefully) the last patch that make PyPI/PIP aware of the `requires_python` metadata (to use in  `setup.py`) for Python-3 only version to not install on Python 2.x (and break for less users)

Once packages can start to be release we at least less fear.

**Comment by lgautier** [comment]
rpy2 is now on board. Closing.
