### ISSUE TITLE
Add OpenQuake to the list of projects

### ISSUE THREAD

**Issue by micheles** [python3statement/python3statement.github.io#76]
We also plan to drop support for Python 3 during the course of the year 2018. Here is the change

```
- [![](assets/openquake.png)OpenQuake engine](https://github.com/gem/oq-engine)
```

and this is the logo:
![openquake](https://cloud.githubusercontent.com/assets/2463856/26192195/01f5d800-3bb1-11e7-82ff-dd400c79dba8.png)

**Comment by takluyver** [comment]
Sorry we missed this - do you want to make a pull request with the change?

**Comment by micheles** [comment]
Could you do that, please?

**Comment by takluyver** [comment]
How does that look?

**Comment by micheles** [comment]
Perfect, thanks!

**Comment by micheles** [comment]
Some colleague of pointed out that the logo I submitted has a white border which is too large.
Here is a better logo:
![oq-engine-small-trimmed](https://user-images.githubusercontent.com/2463856/34764141-cf771fc2-f5ed-11e7-8477-54f7e54c3eb9.png)
If you could be so kind to change it you would have our most sincere thanks :1st_place_medal:

**Comment by Carreau** [comment]
Done. It should be up now.
