### ISSUE TITLE
Add RDKit to list of projects

### ISSUE THREAD

**Issue by greglandrum** [python3statement/python3statement.github.io#80]
The RDKit is an open-source cheminformatics toolkit that has had Python 3 support for several years and has recently committed to move over completely to Python 3 by 2020:
http://www.mail-archive.com/rdkit-discuss@lists.sourceforge.net/msg06935.html

Here's the text:
```- [![](assets/rdkit.png)RDKit](https://github.com/rdkit/rdkit)```

and the logo:
![rdkit 64](https://user-images.githubusercontent.com/540511/27415947-830f7738-570a-11e7-9673-6649c3fcd17e.png)

And the timeline (hopefully I got this right):
```
'RDKit':[
	    {content: '2014.9.1 - 2019.03.1', start: '2014-09-1', end: '2019-09-1', py2:true},
	    {content: '2019.9.1 -' , start: '2019-09-01', end: '2021-03-01'}
	    ]
```

**Comment by Carreau** [comment]
Thanks, can yo +1 on #81 to make sure I did not get anything wrong ? I also pulled out another logo that has a transparent background instead of white if that's ok.
